### ISSUE TITLE
Github Clone: No access to Tempfolder on Windows

### ISSUE THREAD

**Issue by cpieloth** [cpieloth/BackBacker#7]
`github clone` is not working on Windows, because of access problems of tempfolder.

**Comment by cpieloth** [comment]
Tested on Windows 10 with Python 3.6.2 and 3.7.1 and problem still occurs:
```
python setup.py test -s tests.backbacker.commands.test_git.GitCloneTestCase
...
test_execute_folder (tests.backbacker.commands.test_git.GitCloneTestCase) ... Cloning into 'C:\Users\christof\AppData\Local\Temp\gitCloneTest5x45nj0g\cloned'...
done.
ok
test_execute_url (tests.backbacker.commands.test_git.GitCloneTestCase) ... Cloning into 'C:\Users\christof\AppData\Local\Temp\gitCloneTestvkas4lyh\cloned'...
remote: Enumerating objects: 340, done.
remote: Counting objects: 100% (340/340), done.
remote: Compressing objects: 100% (175/175), done.
Rremote: Total 887 (delta 221), reused 269 (delta 161), pack-reused 547
Receiving objects: 100% (887/887), 161.03 KiB | 0 bytes/s, done.
Resolving deltas: 100% (576/576), done.
ERROR

======================================================================
ERROR: test_execute_url (tests.backbacker.commands.test_git.GitCloneTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "...\backbacker\tests\backbacker\commands\test_git.py", line 18, in tearDown
    self._dst_dir_tmp.cleanup()
  File "...\BackBacker\venv\lib\tempfile.py", line 809, in cleanup
    _shutil.rmtree(self.name)
  File "...\BackBacker\venv\lib\shutil.py", line 507, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "...\BackBacker\venv\lib\shutil.py", line 386, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "...\BackBacker\venv\lib\shutil.py", line 386, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "...\BackBacker\venv\lib\shutil.py", line 386, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  [Previous line repeated 1 more time]
  File "...\BackBacker\venv\lib\shutil.py", line 391, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "...\BackBacker\venv\lib\shutil.py", line 389, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Zugriff verweigert: 'C:\\Users\\christof\\AppData\\Local\\Temp\\gitCloneTestvkas4lyh\\cloned\\.git\\objects\\pack\\pack-c472ea50f661132a1024520161925459e9ecabd0.idx'

----------------------------------------------------------------------
Ran 2 tests in 2.219s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=2 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=2 errors=1 failures=0>
```
